/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/exit': RouteRecordInfo<
      '/settings/exit',
      '/settings/exit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user': RouteRecordInfo<
      '/user',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | '/user/login'
      | '/user/register'
      | '/user/reset-password'
    >,
    '/user/login': RouteRecordInfo<
      '/user/login',
      '/user/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/register': RouteRecordInfo<
      '/user/register',
      '/user/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/reset-password': RouteRecordInfo<
      '/user/reset-password',
      '/user/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/exit.vue': {
      routes:
        | '/settings/exit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user.vue': {
      routes:
        | '/user'
        | '/user/login'
        | '/user/register'
        | '/user/reset-password'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/user/login.vue': {
      routes:
        | '/user/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/register.vue': {
      routes:
        | '/user/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/reset-password.vue': {
      routes:
        | '/user/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
